oazapfts/oazapfts

demo/PetstoreApi.ts
package.json
src/ApiStub.test.ts
src/ApiStub.ts

in order not not rely on a globally available fetch, support easier mocking, etc.

support custom/non-global fetch implementation

---

.vscode/settings.json
demo/PetstoreApi.ts
src/ApiStub.ts
src/generate.ts
src/generateServers.test.ts
src/generateServers.ts

in order to expose all potential URLs and variables of the apis servers.
Given swagger spec:
```json
{
"servers": [
{
"description": "MyApi",
"url": "https://petstore.swagger.io/{version}",
"variables": {
"version": {
"enum": ["v1", "v2"],
"default": "v2"
}
}
}
]
}
```
Usage:
```ts
import { Api, MyApiServer } from './Api.ts';
const api = new Api({ server: new MyApiServer({ version: "v1" }) });
```
I deprecated `ApiOptions["baseUrl"]` in favour of `ApiOptions["server"]` which can either be a string or an object with url prop.
PTAL: @fgnass

feat(generate): create Server classes from API servers

---

package-lock.json
package.json

In order to update to `openapi3-ts@1.3.0` as its used by openapi-v3-types. 
also refresh package lock to latest versions of all deps
fixes type errors when using https://github.com/cotype/build-client with https://github.com/cotype/core

fix(package): use  openapi-v3-types v1.0.21

---

demo/PetstoreApi.ts
src/ApiStub.test.ts
src/ApiStub.ts

Since this can lead to problems when parsing the query. See https://github.com/expressjs/body-parser/issues/289.

fix: don't add an index to arrays

---

README.md

There is no official OpenAPI tooling (though there are two popular open-source Java-based tools).

docs: omit reference to official tooling from README.md

---

demo/api.ts
demo/optimisticApi.ts
demo/petstore.json
src/codegen/generate.ts

When having boolean values in an enum, the code generation fails.
**Enum boolean property in OpenAPI document:**
```json
{
"animal": {
"description": "Always true for a pet",
"enum": [
true
],
"type": "boolean"
}
}
```
**Error:**
```
TypeError: s.replace is not a function
at escapeString (../node_modules/typescript/lib/typescript.js:16266:18)
at escapeNonAsciiString (../node_modules/typescript/lib/typescript.js:16271:13)
at Object.getLiteralText (../node_modules/typescript/lib/typescript.js:13486:34)
at getLiteralTextOfNode (../node_modules/typescript/lib/typescript.js:98322:23)
at emitLiteral (../node_modules/typescript/lib/typescript.js:95932:24)
at pipelineEmitWithHint (../node_modules/typescript/lib/typescript.js:95744:32)
at pipelineEmitWithComments …
```

fix: generate boolean values in enum

---

demo/api.test.ts

Enable all E2E tests, not only the `--optimistic` tests.

test: enable all E2E tests

---

demo/api.ts
demo/optimisticApi.ts
src/codegen/generate.ts
src/runtime/index.ts

Make the requestBody an optional method parameter when the `required` parameter isn't defined or has a `false` value.
More info on the requestBody property: https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.2.md#requestBodyObject

fix: respect requestBody required property

---

.github/workflows/ci.yml
.travis.yml
README.md

Replaces Travis with Github actions, which integrates more tightly with Github and allows forks of the repository to run builds as well.

Replace Travis with Github Actions

---

.github/dependabot.yml

Dependabot will create PRs to keep the dependencies up-to-date automatically.

Add Dependabot config to keep dependencies up-to-date

---

demo/jest.config.ts
jest.config.ts
package-lock.json
package.json
tsconfig.json

Allows the Jest configuration to be written in TypeScript, getting all the benefits of it there as well.

Convert Jest configuration to TypeScript

---

src/codegen/generate.ts
src/codegen/index.ts

This prevents newer (v3) OpenAPI specs from being parsed with the legacy behavior for parameters using square brackets to represent a 'deepObject'. In OpenAPI v3 one can simply provide `style: deepObject` to represent these types, and provide a `type: object` with the correct fields.
For more information about these differences, see this [Stack Overflow post](https://stackoverflow.com/a/48498055/1056885).
The main motivation we have to make this change is to make it possible to pass in a schema that has both `foo` and `foo[field]`. If we were to keep the legacy behavior this would mean that we would get two parameters from `supportDeepObjects()` with the same name, which produces incorrect code as we get a type with the same field appearing twice.
For example, the following schema will …

Do not convert bracket-style deepObject parameters for newer OpenAPI

---

src/codegen/generate.ts
src/runtime/index.ts

This allows JSON Hypertext Application Language (HAL) responses with the content type `application/hal+json`. Also cleans up some code so that the content types are no longer duplicated in the code generation.

Allow application/hal+json response types

---

src/codegen/generate.ts

Fixes #45
Actual code change is on lines 404-405.
Open API spec with:
```js
...
"ExStatus": {
"enum": [
0,
1,
2
],
"type": "integer",
"format": "int32"
},
...
```
should now output as:
```ts
export type ExStatus = 0 | 1 | 2;
```
Additional changes are from Husky hooks to format code.

Fix: Handle numeric enum from OpenAPI spec

---

src/codegen/generate.ts
src/runtime/index.ts

From experience, some well defined apis define their error types in open api specs, and those may be of the type `application/problem+json`:  https://datatracker.ietf.org/doc/html/rfc7807.
This PR adds support for this content type just as it has for `application/hal+json`

Allow application/problem+json response types

---

demo/api.test.ts
demo/api.ts
demo/optimisticApi.ts
demo/petstore.json
package-lock.json
package.json
src/runtime/index.ts

Hi cellular team,
I started implementing Blob support as described in #54. Failing Tests as well as the widened type is implemented now. Currently I am struggeling to make the newly added test pass. 
I understand, [open-api-mocker](https://www.npmjs.com/package/open-api-mocker) is being used to mock an api based on petstore.json. All tests pass except my newly added test, that tests blob support. `open-api-mocker` responds with statuscode 400, although I am sure, the test should pass. Unfortunately documentation for `open-api-mocker` is nearly non-existent. Do you have a hint how to debug `open-api-mocker`'s response. Or do you have a different idea for testing?

Extended blob support

---

demo/geojson.json
src/codegen/generate.test.ts
src/codegen/generate.ts
src/runtime/index.ts

Some well defined apis define their geojson types in OpenAPI specs, and those may be of the type `application/geo+json`: https://datatracker.ietf.org/doc/html/rfc7946. 
This include some of the API specs I am using, which when using this type today to render TS oazapfts unfortunately ends up using the Blob data type.
This PR adds support for this content type just as it has for `application/hal+json` and `application/problem+json`.
In short, this PR is based on the recently merged https://github.com/cellular/oazapfts/pull/197 one.

Allow application/geo+json response types

---

demo/api.test.ts
demo/api.ts
demo/optimisticApi.ts
demo/petstore.json
src/codegen/generate.ts
src/runtime/query.ts

As described in https://github.com/cellular/oazapfts/issues/269, we were not handling object parameters according to swagger specification.
BREAKING CHANGE:
When `style` and/or `explode` are not explicitly set on a path parameter in your swagger.json
Then in the past oazapfts had send an array as `?key=a,b`
From now on the same data is sent as `?key=a&key=b`
Also space and pipe delimited serialization now requires explicit disabling of explode to be effective
**Migration:**
When your backend implements the OpenAPI Specification correctly, you do not need to do anything.
If not, or you're unsure, in your swagger.json:
- Set `"explode": false` on all array and object path parameters that had no explicit explode setting before
- Except for object parameters with `"style": "deepObject"`. …

serialize object query parameters as exploded form by default

---

demo/const.json
src/codegen/generate.test.ts
src/codegen/generate.ts

Closes #291 
I implemented this by strictly interpreting the spec which states that "const" is just shorthand for an enum with a single value.
I did notice that enum values right now are restricted to primitive types, when technically object literals are valid (though I've never had a use case for them). I started to take a stab at providing support, but it was a little trickier than I thought since an ObjectLiteralExpression does not extend TypeNode, and I couldn't figure out how to reconcile that difference without altering the fundamental return type of many of the library's methods. Regardless, it was sufficiently complex enough to deserve its own PR if there is interest.

feat: add support for 'const' keyword

---

README.md

When I click on the pronunciation link I'm directed to go to https://youtu.be/chvb-K95rBE, but that page doesn't load for me.
Maybe it's something that's wrong with my network or computer, but the full link works for me https://www.youtube.com/watch?v=chvb-K95rBE

fix pronunciation YouTube link

---

README.md
demo/enumApi.ts
demo/optimisticApi.ts
demo/petstore.json
package.json
src/codegen/cli.ts
src/codegen/generate.test.ts
src/codegen/generate.ts
src/codegen/index.ts

Using the CLI or the API passing the option `--useEnumType` will convert the enums to typescript enums instead of using a union of strings.
This solves #27.
The components property is only available on the OpenAPI v3. Therefore to make it compatible with the OpenAPI v2 I analyzed the enum values and created the enums based on their title property or in the lack of it the name of the property.
Added some tests and documentation to match this new feature.

Adding an option to generate typescript enum instead of union of strings

---

demo/api.ts
demo/enumApi.ts
demo/optimisticApi.ts
demo/petstore.json
src/codegen/generate.test.ts
src/codegen/generate.ts

Currently, the generator separately avoids name conflicts between types on the one hand and enums on the other hand. Interdependend name conflicts between types and enums are still possible. This PR attempts to fix this.
Besides that, thanks for your great tool!

Avoid name conflicts between types and enums

---

src/index.ts
src/runtime/index.test.ts

close https://github.com/oazapfts/oazapfts/issues/390
I have a use case like this:
```ts
try {
await ok(...);
} catch (e) {
if (e instanceof HttpError) {
console.log(e.headers.get("x-request-id"));
}
throw e;
}
```
`oazapfts.fetchText` and `oazapfts.fetchJson` already return response with headers, so it doesn't change generated code, only runtime code and types.

Throw error with HTTP headers

---

src/runtime/index.test.ts
src/runtime/index.ts

This Pull Request attempts to allow the `Content-Type` header to be customized.
Here's a little more context about the reason for this proposal: https://github.com/oazapfts/oazapfts/issues/452
Hi @Xiphe 
In our conversation to allow this (https://github.com/oazapfts/oazapfts/issues/452), you commented:
> Gave this another thought. I think just switching out the lines should be treated as a breaking change ...
But I wasn't sure if you were just not convinced about switching these lines. 
I gave some thoughts about how these changes could affect negatively another user but I think it would only be an issue if they have an unnoticed modification of the `Content-Type` header. But of course, I could totally be missing some scenarios.
Please let me know if you think we should go for a more …

Customize 'Content-Type' header

---

README.md
demo/api.test.ts
demo/api.ts
demo/enumApi.ts
demo/mergedReadWriteApi.ts
demo/optimisticApi.ts
demo/petstore.json
package.json
src/codegen/__fixtures__/readOnlyWriteOnly.yaml
src/codegen/generate.ts
src/codegen/index.test.ts

Supersedes: https://github.com/oazapfts/oazapfts/pull/450
The existing implementation for [handling read-/writeonly](https://github.com/oazapfts/oazapfts/issues/382) ignored `array`, `$ref` and other nested types, which caused some properties to become missing on those nested objects.
This fix now always creates all applicable read/write extensions for a type and takes nested/linked types into account when determining if a type has readonly or writeonly qualities.
Also keeps the `--mergeReadWriteOnly` flag from #450 around to support opting out of the the behavior altogether.
@cvereterra would you mind having a look on this?
Also PTAL/FYI @fgnass @jonkoops @ehvattum

Handle nested objects and $refs in read-/writeonly types

---

src/codegen/__fixtures__/prefixItems.json
src/codegen/generate.ts
src/codegen/index.test.ts

Closes #461
I simply added another if statement and added the prefixItems to the SchemaObject type.
Also would you like me to add a test?
Are you using prettier or something, mine seems to be on different settings.

Add prefixItems to type generation

---

src/codegen/__fixtures__/allOf.json
src/codegen/generate.ts
src/codegen/index.test.ts

Closes #422 
This PR adds support for the discriminator used in conjunction with `allOf` constructor. See the added tests for an example. Several key concepts are introduced in this PR:
1. `metadata` property: A new property called `metadata` has been added to the `SchemaObject`. This property contains information added by oazapft. As of now, only the `selfRef` is present in the `SchemaMetadata` type, but other properties may be added in the future.
2. parent schema: The term "parent schema" appears in several places. In this context, it refers to a schema that has a `discriminator` property which is neither used in conjunction with `oneOf` nor `anyOf`. This is also described in the comment of `preprocessSchemas`.
3. `ignoreDiscriminator` parameter: In order to support the discriminator …

Support discriminator with allOf

---

src/codegen/__fixtures__/recursive.yaml
src/codegen/generate.ts
src/codegen/index.test.ts

Closes #486 
In the current implementation, `checkSchemaOnlyMode` does not work for recursive schemas (i.e. encounter inifinite recursion). This PR addresses the problem.

Prevent infinite recursion of checkSchemaOnlyMode

---

src/codegen/generate.ts

The following code has been moved from `generateApi()` to `constructor()`.
```typescript
if (this.spec.components?.schemas) {
this.preprocessComponents(this.spec.components.schemas);
}
```
The motivation behind this change is described in #491.

Do preprocessing in the constructor

---

src/codegen/__fixtures__/oneOfMerge.yaml
src/codegen/generate.ts
src/codegen/index.test.ts

This commit introduces an enhancement to better handle the oneOf schema in OpenAPI definitions.
- Added a new OpenAPI test fixture - oneOfMerge.yaml
- Updated logic in the codegen script where oneOf schemas are encountered. The properties of the schema are now deeply merged to accommodate different variations.
- Added a new test case to confirm the improved handling of oneOf schemas.
```yaml
openapi: 3.0.3
info:
title: OneOfMerge
version: 0.1.0
paths:
/mix:
get:
description: stats
parameters:
- name: param1
in: query
schema:
oneOf:
- required:
- c
properties:
a:
type: string
- required:
- b
properties:
b:
type: string
required:
- d
properties:
c:
type: string
d:
enum:
- enum1
- enum2
type: string
responses:
"200":
description: ok
```
```ts
/** * OneOfMerge * 0.1.0 * DO NOT MODIFY - This …
```

[Enhancement] Improve oneOf schema handling

---

demo/api.ts
demo/enumApi.ts
demo/mergedReadWriteApi.ts
demo/optimisticApi.ts
src/codegen/generate.ts

This emits `SchemaObject.description` in a multi-line comment in front of the property.
This makes sure useful documentation is included in the generated code.

feat: Include property descriptions

---

demo/api.test.ts
demo/api.ts
demo/enumApi.ts
demo/mergedReadWriteApi.ts
demo/optimisticApi.ts
src/codegen/generate.ts
src/runtime/headers.ts
src/runtime/index.test.ts
src/runtime/index.ts
src/runtime/util.ts

- stop setting Content-Type header for multipart requests
- support HeaderInit in request objects
- support default headers
BREAKING CHANGE:
multipart/form-data headers are not set by oazapfts anymore as these are usually automatically set by the browser/node when this causes problems on your end you can set Content-Type=multipart/form-data manually via RequestOpts
oazapfts runtime now works with `Header` instead of plain Objects `{}`. This might affect you when you use a custom fetch implementation and manipulate headers there
oazapfts no longer safe-guards "Content-Type" headers
in the past we discarded custom Content-Type headers that didn't start with `json` for json requests
and similarly Content-Type headers that didn't start with application/x-www-form-urlencoded for form requests …

Smarter header defaults and handling

---

src/codegen/generate.ts

Fixes https://github.com/oazapfts/oazapfts/issues/545.
Before:
```ts
/** The URL of the configuration page for the time tracking provider app. For example, */example/config/url*. This property is only returned if the `adminPageKey` property is set in the module descriptor of the time tracking provider app. */
url?: string;
```
After:
```ts
/** The URL of the configuration page for the time tracking provider app. For example, *\/example/config/url*. This property is only returned if the `adminPageKey` property is set in the module descriptor of the time tracking provider app. */
url?: string;
```

Escape any comment closing tags in schema descriptions

---

README.md
demo/objectStyleArgument.ts
package.json
src/codegen/cli.ts
src/codegen/generate.ts
src/codegen/index.test.ts
src/codegen/index.ts

This PR adds an option that lets us opt in to object style argument by `--argumentStyle=object`:
```typescript
export function updatePetWithForm({ petId, body }: {
petId: number;
body?: {
/** Updated name of the pet */
name?: string;
/** Updated status of the pet */
status?: string;
};
}, opts?: Oazapfts.RequestOpts) {
return oazapfts.fetchText(`/pet/${encodeURIComponent(petId)}`, oazapfts.form({
...opts,
method: "POST",
body
}));
}
```
as opposed to `--argumentStyle=positional` one (which is default):
```typescript
export function updatePetWithForm(petId: number, body?: {
/** Updated name of the pet */
name?: string;
/** Updated status of the pet */
status?: string;
}, opts?: Oazapfts.RequestOpts) {
return oazapfts.fetchText(`/pet/${encodeURIComponent(petId)}`, oazapfts.form({
...opts, …
```

feat: add --argumentStyle option

---

package.json

The changes made in https://github.com/oazapfts/oazapfts/commit/768ddd404ea256a46b92af949e444133119c5bd6 broke my build with the following webpack error after running `next build`:
```ts
Module not found: Default condition should be last one
6 |  * See https://www.npmjs.com/package/oazapfts
7 |  */
>  8 | import * as Oazapfts from "oazapfts/lib/runtime";
9 | import * as QS from "oazapfts/lib/runtime/query";
10 | export const defaults: Oazapfts.Defaults<Oazapfts.CustomHeaders> = {
11 |     headers: {},
https://nextjs.org/docs/messages/module-not-found
```
According to the [webpack documentation](https://webpack.js.org/guides/package-exports/#conditional-syntax):
> The last condition in the object might be the special "default" condition, which is always matched.
Since the `default` …

fix: move default exports to bottom

---

src/codegen/__fixtures__/array-type.yaml
src/codegen/generate.ts
src/codegen/index.test.ts

OpenAPI spec 3.1.0 supports type arrays (s. [Migration Guide](https://www.openapis.org/blog/2021/02/16/migrating-from-openapi-3-0-to-3-1-0)) and thus becomes [JSON schema compliant](https://json-schema.org/understanding-json-schema/reference/type), e.g.:
```
type:
- "object"
- "null" 
```
As far is I understand this is not yet implemented or reflected in this code base. This is an attempt to add the necessary functionality. Please let me know if there are any more changes that need to be made in order to meet the code quality requirements.
closes #497

Support type arrays according to OpenAPI spec 3.1.0

---

packages/codegen/src/tscodegen.ts

Fixes #626
Typescript >= 5.4 raises an error when using the method createNumericLiteral with a negative number
https://github.com/microsoft/TypeScript/blob/v5.4-rc/src/compiler/factory/nodeFactory.ts#L1257
This pr uses createPrefixUnaryExpression in combination with createNumericLiteral to handle negative numbers.

fix(codegen): create negative numbers with createNumericLiteral in combination with createPrefixUnaryExpression

---

packages/codegen/src/__fixtures__/booleanSchema.json
packages/codegen/src/__fixtures__/booleanSchemaRefs.json
packages/codegen/src/generate.ts
packages/codegen/src/index.test.ts
packages/codegen/src/tscodegen.ts

oazapfts codegen fails if the api contains [boolean json schema](https://json-schema.org/draft/2020-12/json-schema-core#section-4.3.2).
```jsonc
{
// ...
"schemas": {
"Foo": {
"type": "object",
"required": ["bar"],
"properties": {
"bar": true
},
"additionalProperties": false
}
}
}
```
This PR adds support for these, mapping `true` to `any` and `false` to `never`.
I am not sure about how this should behave with "TrueEnums" (~~not sure what that is~~ i get it now, these are typescript enums), so please review with extra care, as I am not familiar with the codebase and don't understand every corner of it.
This is an upstream issue with `kogosoftwarellc/open-api`, which is also missing boolean schema support (I filed a PR to fix this at kogosoftwarellc/open-api#902).

fix: support boolean schemas

---

packages/codegen/src/generate.test.ts
packages/codegen/src/generate.ts

In a discriminated union, use the provided variant name instead of the schema`s name. use the Schema’s name only if it’s not provided.
For example, here the variant name `standard` is given, and is used instead of the schema’s name `StandardAllowance` (which was previously used, and would result in invalid, empty type (because the string has to match discriminated union with 
```yaml
Allowance:
oneOf:
- $ref: "#/components/schemas/EngineeringAllowance"
- $ref: "#/components/schemas/StandardAllowance"
discriminator:
propertyName: allowance_type
```
```yaml
StandardAllowance:
properties:
allowance_type:
type: string
enum: ["standard"]
```
This now creates a valid discriminated union. The `allowance_type` field in the variants matches with the `allowance_type` in the discriminated unions : …

discriminated unions with enum variant

---

demo/api.ts
demo/enumApi.ts
demo/mergedReadWriteApi.ts
demo/objectStyleArgument.ts
demo/optimisticApi.ts
demo/petstore.json
packages/codegen/src/generate.ts

very similar to #626 , but this time while creating numeric enums:
```
> generate-api
> oazapfts ../src/backend/web/static/swagger/api_v3.json --argumentStyle=object --useEnumType > app/api/v3.ts
/home/justin/code/frc/the-blue-alliance/pwa/node_modules/typescript/lib/typescript.js:25239
Debug.assert(text.charCodeAt(0) !== 45 /* minus */, "Negative numbers should be created in combination with createPrefixUnaryExpression");
^
Error: Debug Failure. False expression: Negative numbers should be created in combination with createPrefixUnaryExpression
at Object.createNumericLiteral (/home/justin/code/frc/the-blue-alliance/pwa/node_modules/typescript/lib/typescript.js:25239:11)
at file:///home/justin/code/frc/the-blue-alliance/pwa/node_modules/oazapfts/tscodegen-wH2Xseqv.js:543:13
at Array.map …
```

fix: negative numeric values in enums

---

demo/api.ts
demo/enumApi.ts
demo/mergedReadWriteApi.ts
demo/objectStyleArgument.ts
demo/optimisticApi.ts
demo/petstore.json
packages/codegen/src/generate.ts

Ran into an issue trying to generate types for a schema that had a discriminator defined without mapping. The missing mapping was caused by the generated OpenAPI spec having poorly parsed inheritance.
The following will result in `export type MyAlias = ;`, with the conditional change it will fall back to `export type MyAlias = {};`
```json
"MyAlias": {
"required": ["@type"],
"type": "object",
"properties": {},
"discriminator": { "propertyName": "@type" }
},
```

fix: ignore undefined discriminator mapping

---

demo/api.ts
demo/enumApi.ts
demo/mergedReadWriteApi.ts
demo/objectStyleArgument.ts
demo/optimisticApi.ts
demo/petstore.json
packages/codegen/src/generate.ts
packages/codegen/src/index.test.ts

An array of enums is handled incorrectly when the useEnumType option is enabled.

feat: added enum array support

---

packages/codegen/src/__fixtures__/allOf.json
packages/codegen/src/generate.ts
packages/codegen/src/index.test.ts
packages/codegen/src/index.ts

When generating code from a schema like this
```
"Pet": {
"type": "object",
"properties": {
"petType": {
"type": "string"
}
},
"required": ["petType"],
"discriminator": {
"propertyName": "petType",
"mapping": {
"dog": "#/components/schemas/Dog",
"poodle": "#/components/schemas/Dog",
"cat": "#/components/schemas/Cat"
}
}
}
```
I would expect to see the following TypeScript output
```ts
export type PetBase = { petType: string };
export type Dog = { petType: "dog" | "poodle" } & PetBase & { bark?: string };
export type Cat = { petType: "cat" } & PetBase & { name?: string };
export type Pet = Dog | Cat;
```
However, `oazapfts` generates the following instead
```ts
export type PetBase = { petType: string };
export type Dog = { petType: "dog" } & PetBase & { bark?: string };
export type Cat = { …
```

Fix issue with enum discriminators
